name: pyCADD
channels:
  - conda-forge
dependencies:
  - rich>=10.16
  - scikit-learn
  - pandas
  - openpyxl
  - openbabel>=3.1.0
  - pyyaml>=6.0
  - click
  - scipy
  - xlsxwriter>=3.0 
  - openpyxl
  - requests
  - ambertools>=23.6
  - pip:
    - concurrent_log_handler>=0.9.20
